train_dataset:
  type: Cityscapes
  dataset_root: /home/aistudio/data/data64550/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: /home/aistudio/data/data64550/cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: HRNetW48ContrastHead
  backbone:
    type: HRNet_W48
  in_channels: 720
  num_classes: 19
  drop_prob: 0.1
  proj_dim: 720

optimizer:
  type: sgd
  weight_decay: 0.0002

lr_scheduler:
  type: ReduceOnPlateau
  learning_rate: 0.1
  mode: max
  factor: 0.7
  patience: 1
  verbose: True
iters: 600000
batch_size: 4

loss:
  types:
    - type: CrossEntropyLoss
    - type: PixelContrastCrossEntropyLoss
      temperature: 0.1
      base_temperature: 0.07
      ignore_index: 255
      max_samples: 1024
      max_views: 100
  coef: [1, 0.1]
  
